# This is a basic workflow to help you get started with Actions

name: Branch Created

# Controls when the action will run. 
on:
  # Triggers the workflow on creation of a branch
  create:

  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout
          uses: actions/checkout@v2

        #Find Branch Name and Outputs it as branch VARIABLE
        - name: Extract branch name
          shell: bash
          run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: extract_branch

        # Makes sh EXC
        - name: Make CreatedBranch.sh executable
          run: 
            git update-index --add --chmod=+x scripts/createdbranch.sh

        # Runs a command
        - name: Run CreatedBranch.sh
          shell: bash
          run: scripts/createdbranch.sh
          env:
            BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
            