# This is a basic workflow to help you get started with Actions

name: Build Production

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # workflow_run:
  #   workflows: ["Validate Production"]
  #   types: [completed]
  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  #on-success:
  build:
    runs-on: ubuntu-latest
    
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout
          uses: actions/checkout@v2

        # Runs a command
        - name: Run LoadMetadata.sh
          run: scripts/loadMetadata.sh
          env:
            SANDBOX_NAME: Production
            SFUSER: ${{ secrets.PROD_USERNAME }}
            SFPASSWORD: ${{ secrets.PROD_PASSWORD }}
            CHECKONLY: FALSE
            TESTLEVEL: RunSpecifiedTests
          
  # on-failure:        
  #   runs-on: ubuntu-latest
    
  #   if: ${{ github.event.workflow_run.conclusion == 'failure' }}
