name: retrieveMetadata From Dev Staging Environment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #Commented out whilst system is in Manual Mode v
  #create:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      # Runs a command
      - name: Run retrieveMetadataAndPushToGit.sh
        run: scripts/retrieveMetadataAndPushToGit.sh
        env:
          SFUSER: ${{ secrets.STAGING_USERNAME }}
          SFPASSWORD: ${{ secrets.STAGING_PASSWORD }}
          GITUSERNAME: ${{ secrets.GITUSERNAME }}
          GITPASSWORD: ${{ secrets.GITPASSWORD }}
          ENV: DevStaging
