# This is a basic workflow to help you get started with Actions

name: Validate CI With Org Wide Test Run

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: 
    - release/*
    - sprint/*
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a command
      - name: Run LoadMetadata.sh
        run: scripts/loadMetadata.sh
        env:
          SANDBOX_NAME: CI
          SFUSER: ${{ secrets.CI_USERNAME }}
          SFPASSWORD: ${{ secrets.CI_PASSWORD }}
          CHECKONLY: true
          TESTLEVEL: ${{ secrets.ORGWIDE_TESTLEVEL }}
          

